In [ ]:
from selenium import webdriver
import pandas as pd
import time
import os
import numpy as np
pd.set_option('display.max_colwidth', None) # stop truncating long text
url = "https://www.goodreads.com/list/best_of_year/2025"

Data Collection / Mining

In [181]:
df = pd.DataFrame(columns=["book_title","publication_date","author","genres","ratings",
                           "num_pages","rank","language","curr_readers","want_read"])
# scrape page
driver = webdriver.Chrome()
for i in range(1,7):
    driver.get(f'https://www.goodreads.com/list/best_of_year/2025?id=222558.Best_Books_of_2025&page={i}')
    time.sleep(.5)

    # close popup on list page if it exists
    try:
        popup = driver.find_element('xpath','/html/body/div[3]/div/div/div[1]/button/img')
        popup.click()
        print("popup closed")
    except:
        print("no popup")
        pass

    books = driver.find_elements('xpath', "//tr[contains(@itemtype, 'schema.org/Book')]")

    # extract list-page info
    book_data = []
    for book in books:
        rank = book.find_element('xpath', ".//td[contains(@class, 'number')]").text
        book_title = book.find_element('xpath', ".//a[contains(@class, 'bookTitle')]").text
        ratings = book.find_element('xpath', ".//span[contains(@class, 'minirating')]").text
        author = book.find_element('xpath', ".//a[contains(@class, 'authorName')]").text
        book_link = book.find_element('xpath', ".//a[contains(@class, 'bookTitle')]").get_attribute("href")
        
        book_data.append({
            "rank": rank,
            "book_title": book_title,
            "ratings": ratings,
            "author": author,
            "book_link": book_link
        })

    # visit each book link
    for item in book_data:
        driver.get(item["book_link"])
        time.sleep(.5)

        # close popup on book page if it exists
        try:
            popup = driver.find_element('xpath','/html/body/div[3]/div/div[1]/div/div/button')
            popup.click()
            print("popup closed")
        except:
            print("no popup")
            pass
        try:
            publication_date = driver.find_element('xpath','//p[contains(@data-testid, "publicationInfo")]').text
        except:
            publication_date =""
        try:
            genres = driver.find_elements('xpath','//span[contains(@class, "BookPageMetadataSection__genreButton")]')
            genres = [genre.text for genre in genres]
            genres = ", ".join(genres)
        except:
            genres = ""
        try:
            num_pages = driver.find_element('xpath','//p[contains(@data-testid, "pagesFormat")]').text
        except:
            num_pages = ""
            
        try:
            more_button = driver.find_element('xpath','//button[contains(@aria-label, "Book details and editions")]')
            more_button.click()
            time.sleep(.5)
        except:
            pass
        try:
            language = driver.find_element('xpath',"//dt[normalize-space()='Language']/following-sibling::dd[1]//div[@data-testid='contentContainer']").text
            print("Language:", language)
        except:
            language =""
            print("Language not found.")
        try:
            num_reading = driver.find_element('xpath','//div[contains(@data-testid, "currentlyReadingSignal")]').text
        except:
            num_reading = ""
        try:
            num_want_read = driver.find_element('xpath','//div[contains(@data-testid, "toReadSignal")]').text
        except:
            num_want_read = ""
        print("finished scraping", item["book_title"])
        df.loc[len(df)] = [
            item["book_title"],
            publication_date,
            item["author"],
            genres,
            item["ratings"],
            num_pages,
            item["rank"],
            language,
            num_reading,
            num_want_read
        ]
driver.quit()

no popup
popup closed
Language not found.
finished scraping Sunrise on the Reaping (The Hunger Games, #0.5)
no popup
Language not found.
finished scraping Onyx Storm (The Empyrean, #3)
no popup
Language: English
finished scraping Atmosphere
no popup
Language: English
finished scraping My Friends
no popup
Language: English
finished scraping Wild Dark Shore
no popup
Language: English
finished scraping Deep End
no popup
Language: English
finished scraping Great Big Beautiful Life
no popup
Language not found.
finished scraping The Favorites
no popup
Language: English
finished scraping Rebel Witch (The Crimson Moth, #2)
no popup
Language not found.
finished scraping Everything Is Tuberculosis: The History and Persistence of Our Deadliest Infection
no popup
Language: English
finished scraping Broken Country
no popup
Language: English
finished scraping The Names
no popup
Language not found.
finished scraping Beg, Borrow, or Steal (When in Rome, #3)
no popup
Language not found.
finished scraping The House of My Mother: A Daughter's Quest for Freedom
no popup
Language: English
finished scraping Katabasis
no popup
Language: English
finished scraping First-Time Caller (Heartstrings, #1)
no popup
Language: English
finished scraping Alchemised
no popup
Language: English
finished scraping Say You'll Remember Me (Say You'll Remember Me, #1)
no popup
Language: English
finished scraping Rewind It Back (Windy City, #5)
no popup
Language not found.
finished scraping Emily Wilde's Compendium of Lost Tales (Emily Wilde, #3)
no popup
Language: English
finished scraping Witchcraft for Wayward Girls
no popup
Language: English
finished scraping Fearless (The Powerless Trilogy, #3)
no popup
Language: English
finished scraping The Crash
no popup
Language not found.
finished scraping Problematic Summer Romance (Not in Love, #2)
no popup
Language: English
finished scraping The Fall Risk (Valentine's Day #2)
no popup
Language: English
finished scraping The Tenant
no popup
Language: English
finished scraping The Road to Tender Hearts
no popup
Language: English
finished scraping I Am Not Jessica Chen
no popup
Language: English
finished scraping The Correspondent
no popup
Language: English
finished scraping Flesh
no popup
Language: English
finished scraping One Golden Summer
no popup
Language: English
finished scraping Tilt
no popup
Language: English
finished scraping Scythe & Sparrow (The Ruinous Love Trilogy, #3)
no popup
Language: English
finished scraping The Knight and the Moth (The Stonewater Kingdom, #1)
no popup
Language: English
finished scraping Raising Hare: A Memoir
no popup
Language not found.
finished scraping Bury Our Bones in the Midnight Soil
no popup
Language not found.
finished scraping Good Dirt
no popup
Language: English
finished scraping The River Has Roots
no popup
Language not found.
finished scraping A Drop of Corruption (Shadow of the Leviathan, #2)
no popup
Language not found.
finished scraping The Buffalo Hunter Hunter
no popup
Language: English
finished scraping Beautiful Ugly
no popup
Language: English
finished scraping The Hounding
no popup
Language: English
finished scraping The Inheritance (Breach Wars, #1)
no popup
Language not found.
finished scraping When the Moon Hits Your Eye
no popup
Language: English
finished scraping Silver Elite (Silver Elite, #1)
no popup
Language not found.
finished scraping King of Envy (Kings of Sin, #5)
no popup
Language not found.
finished scraping Enchantra (Wicked Games, #2)
no popup
Language: English
finished scraping Too Old for This
no popup
Language: English
finished scraping Penitence
no popup
Language: English
finished scraping We All Live Here
no popup
Language: English
finished scraping Not Quite Dead Yet
no popup
Language: English
finished scraping The Strength of the Few (Hierarchy, #2)
no popup
Language: English
finished scraping King Sorrow
no popup
Language: English
finished scraping Audition
no popup
Language: English
finished scraping Accomplice to the Villain (Assistant to the Villain, #3)
no popup
Language: English
finished scraping The River Is Waiting
no popup
Language: English
finished scraping This Princess Kills Monsters
no popup
Language: English
finished scraping Releasing 10 (Boys of Tommen, #6)
no popup
Language: English
finished scraping Death of the Author
no popup
Language not found.
finished scraping Till Summer Do Us Part
no popup
Language not found.
finished scraping Swept Away
no popup
Language not found.
finished scraping The Maid's Secret (Molly the Maid, #3)
no popup
Language: English
finished scraping The Impossible Fortune (Thursday Murder Club, #5)
no popup
Language: English
finished scraping The Love Haters
no popup
Language not found.
finished scraping The Emperor of Gladness
no popup
Language: English
finished scraping Caught Up (Into Darkness, #2)
no popup
Language: English
finished scraping Junie
no popup
Language: English
finished scraping Promise Me Sunshine
no popup
Language: English
finished scraping Watch Me (Shatter Me: The New Republic, #1)
no popup
Language: English
finished scraping The Wrath of the Fallen (Gods & Monsters, #4)
no popup
Language: English
finished scraping Water Moon
no popup
Language: English
finished scraping The Rose Bargain (The Rose Bargain, #1)
no popup
Language: English
finished scraping The Intruder
no popup
Language: English
finished scraping Of Flame and Fury
no popup
Language: English
finished scraping Dream Count
no popup
Language: English
finished scraping Here Beside the Rising Tide
no popup
Language: English
finished scraping Wild and Wrangled (Rebel Blue Ranch, #4)
no popup
Language: English
finished scraping Eldritch (The Eating Woods, #2)
no popup
Language: English
finished scraping Proto: How One Ancient Language Went Global
no popup
Language: English
finished scraping Theft
no popup
Language not found.
finished scraping Dream Girl Drama (Big Shots, #3)
no popup
Language not found.
finished scraping Sky Daddy
no popup
Language: English
finished scraping A Curious Kind of Magic
no popup
Language: English
finished scraping The Man Made of Smoke
no popup
Language: English
finished scraping The Shattering Peace (Old Man's War, #7)
no popup
Language: English
finished scraping My Inconvenient Duke (Difficult Dukes, #3)
no popup
Language: English
finished scraping Blood on Her Tongue
no popup
Language: English
finished scraping Julie Chan Is Dead
no popup
Language: English
finished scraping I See You've Called in Dead
no popup
Language: English
finished scraping More or Less Maddy
no popup
Language not found.
finished scraping Mate (Bride, #2)
no popup
Language: English
finished scraping The Floating World (The Floating World, #1)
no popup
Language: English
finished scraping You Weren't Meant to Be Human
no popup
Language: English
finished scraping Shield of Sparrows (Shield of Sparrows, #1)
no popup
Language: English
finished scraping Dire Bound (The Wolves of Ruin, #1)
no popup
Language: English
finished scraping Out of the Woods (Out, #2)
no popup
Language: English
finished scraping Bat Eater and Other Names for Cora Zeng
no popup
Language not found.
finished scraping Hemlock & Silver
no popup
Language: English
finished scraping The Paris Express
no popup
Language: English
finished scraping Cat's People
no popup
no popup
Language not found.
finished scraping The Missing Half
no popup
Language: English
finished scraping Good Girl
no popup
Language: English
finished scraping Don't Open Your Eyes
no popup
Language not found.
finished scraping Saga #71
no popup
Language: English
finished scraping A Witch's Guide to Magical Innkeeping
no popup
Language not found.
finished scraping Somewhere Toward Freedom: Sherman's March and the Story of America's Largest Emancipation
no popup
Language: English
finished scraping Saga #72
no popup
Language not found.
finished scraping Wild Side (Rose Hill, #3)
no popup
Language: English
finished scraping The Bright Years
no popup
Language not found.
finished scraping Left of Forever (Spunes, OR, #2)
no popup
Language not found.
finished scraping Vera Wong's Guide to Snooping [On a Dead Man] (Vera Wong, #2)
no popup
Language not found.
finished scraping Automatic Noodle
no popup
Language: English
finished scraping Deep Cuts
no popup
Language: English
finished scraping Phantom (Cat and Mouse, #0)
no popup
Language not found.
finished scraping A Curse Carved in Bone (Saga of the Unfated, #2)
no popup
Language not found.
finished scraping Sounds Like Love
no popup
Language: English
finished scraping The Inheritance
no popup
Language: English
finished scraping Homeseeking
no popup
Language: English
finished scraping A Fate Forged in Fire
no popup
Language: English
finished scraping When the Wolf Comes Home
no popup
Language: English
finished scraping Old Soul
no popup
Language: English
finished scraping The Lamb
no popup
Language: English
finished scraping The Raven Scholar (Eternal Path Trilogy, #1)
no popup
Language not found.
finished scraping Big Dumb Eyes: Stories from a Simpler Mind
no popup
Language: English
finished scraping Shadow Ticket
no popup
Language: English
finished scraping Return to Sender (Walt Longmire, #21)
no popup
Language: English
finished scraping The Pretender
no popup
Language not found.
finished scraping The Frozen People (Ali Dawson, #1)
no popup
Language: English
finished scraping The Expert of Subtle Revisions
no popup
Language not found.
finished scraping The Undercutting of Rosie and Adam (Hart and Mercy, #3)
no popup
Language: English
finished scraping Bonded in Death (In Death, #60)
no popup
Language: English
finished scraping The Dream Hotel
no popup
Language: English
finished scraping What Happened to the McCrays?
no popup
Language not found.
finished scraping All the Water in the World
no popup
Language: English
finished scraping The Martian Contingency (Lady Astronaut Universe, #4)
no popup
Language not found.
finished scraping Love Forms
no popup
Language: English
finished scraping Harriet Tubman: Live in Concert
no popup
Language: English
finished scraping Unloved (The Undone, #2)
no popup
Language not found.
finished scraping Universality
no popup
Language: English
finished scraping Framed in Death (In Death, #61)
no popup
Language not found.
finished scraping Wearing the Lion
no popup
Language not found.
finished scraping Adrift in Currents Clean and Clear (Wayward Children, #10)
no popup
Language: English
finished scraping The Kiss Bet, Vol. 1
no popup
Language: English
finished scraping Sharp Force
no popup
Language: English
finished scraping Cinder House
no popup
Language not found.
finished scraping The Ladies Road Guide to Utter Ruin (The Ill-Mannered Ladies, #2)
no popup
Language: English
finished scraping Kills Well with Others (Killers of a Certain Age, #2)
no popup
Language: English
finished scraping The Perfect Divorce (Perfect, #2)
no popup
Language: English
finished scraping The Thrashers
no popup
Language: English
finished scraping The Library at Hellebore
no popup
Language not found.
finished scraping The Geographer's Map to Romance (Love's Academic, #2)
no popup
Language: English
finished scraping Among the Burning Flowers (The Roots of Chaos, #0.2)
no popup
Language: English
finished scraping This American Woman: A One-in-a-Billion Memoir
no popup
Language not found.
finished scraping The Irresistible Urge to Fall For Your Enemy (Dearly Beloathed, #1)
no popup
Language: English
finished scraping Copper Script
no popup
Language: English
finished scraping Feral, Vol. 2: Cat Lady
no popup
Language: English
finished scraping All the Missing Pieces
no popup
Language: English
finished scraping The South
no popup
Language: English
finished scraping Don't Let Him In
no popup
Language: English
finished scraping Fishflies
no popup
Language: English
finished scraping What Stalks the Deep (Sworn Soldier, #3)
no popup
Language not found.
finished scraping That Devil, Ambition
no popup
Language not found.
finished scraping Apostle's Cove (Cork O'Connor, #20)
no popup
Language not found.
finished scraping The Children of Eve (Charlie Parker, #22)
no popup
Language not found.
finished scraping Mỹ Documents
no popup
Language not found.
finished scraping We Pretty Pieces of Flesh
no popup
Language: English
finished scraping The Fisherman's Gift
no popup
Language not found.
finished scraping The Staircase in the Woods
no popup
Language: English
finished scraping Slap Shot (D.C. Stars, #3)
no popup
Language: English
finished scraping Hot Air
no popup
Language not found.
finished scraping What Kind of Paradise
no popup
Language not found.
finished scraping I Got Abducted by Aliens and Now I'm Trapped in a Rom-Com (Cosmic Chaos, #1)
no popup
Language not found.
finished scraping Faithbreaker
no popup
Language: English
finished scraping Three Days in June
no popup
Language: English
finished scraping Hungerstone
no popup
Language: English
finished scraping Gifted & Talented
no popup
Language: English
finished scraping Brighter than Scale, Swifter than Flame
no popup
Language: English
finished scraping Slayers of Old
no popup
Language: English
finished scraping The Isle in the Silver Sea
no popup
Language: English
finished scraping Vantage Point
no popup
Language not found.
finished scraping Finlay Donovan Digs Her Own Grave (Finlay Donovan, #5)
no popup
Language: English
finished scraping Our Infinite Fates
no popup
Language: English
finished scraping The Stolen Queen
no popup
Language not found.
finished scraping Wild Card (Rose Hill, #4)
no popup
Language not found.
finished scraping Minor Arcana Vol. 1
no popup
Language: English
finished scraping My Name Is Emilia del Valle
no popup
Language: English
finished scraping The Seasons #1
no popup
Language: English
finished scraping Tell Me What You Did
no popup
Language not found.
finished scraping The Next One Is for You: A True Story of Guns, Country, and the IRA’s Secret American Army
no popup
Language: English
finished scraping The Medusa Protocol (Assassins Anonymous, #2)
no popup
Language not found.
finished scraping Mark Twain
no popup
Language: English
finished scraping Exit Strategy (Jack Reacher, #30)
no popup
Language not found.
finished scraping Saga, Volume 12
no popup
Language: English
finished scraping Daedalus Is Dead
no popup
Language: English
finished scraping The Autumn Springs Retirement Home Massacre
no popup
Language: English
finished scraping Tough Luck
no popup
Language not found.
finished scraping Spiral (Off the Ice, #2)
no popup
Language not found.
finished scraping We Are All Guilty Here (North Falls, #1)
no popup
Language: English
finished scraping Never Flinch (Holly Gibney, #4)
no popup
Language not found.
finished scraping The Seasons #2
no popup
no popup
Language not found.
finished scraping Murder at Gulls Nest (Nora Breen Investigates #1)
no popup
Language not found.
finished scraping After Life
no popup
Language: English
finished scraping Book of Cutter #1
no popup
Language: English
finished scraping Count My Lies
no popup
Language: English
finished scraping King of Ashes
no popup
Language: English
finished scraping Last Twilight in Paris
no popup
Language: English
finished scraping Maggie; or, A Man and a Woman Walk Into a Bar
no popup
Language not found.
finished scraping Far and Away
no popup
Language not found.
finished scraping Other People’s Fun
no popup
Language not found.
finished scraping The Enchanted Greenhouse (Spellshop, #2)
no popup
Language: English
finished scraping A Granite Silence
no popup
Language: English
finished scraping The Three Lives of Cate Kay
no popup
Language: English
finished scraping Head Cases (Head Cases, #1)
no popup
Language: English
finished scraping Let the Bad Times Roll
no popup
Language not found.
finished scraping Victorian Psycho
no popup
Language: English
finished scraping A Killing Cold
no popup
Language: English
finished scraping Isola
no popup
Language: English
finished scraping The Beasts We Bury (The Broken Citadel, #1)
no popup
Language: English
finished scraping When the Tides Held the Moon
no popup
Language: English
finished scraping This Book Will Bury Me
no popup
Language: English
finished scraping All the Other Mothers Hate Me
no popup
Language: English
finished scraping Death Row (Alibis Collection, #1)
no popup
Language: English
finished scraping A Sea of Unspoken Things
no popup
Language not found.
finished scraping Fight (Sky Ridge Hotshots, #1)
no popup
Language: English
finished scraping The Sirens
no popup
Language not found.
finished scraping Careless People: A Cautionary Tale of Power, Greed, and Lost Idealism
no popup
Language not found.
finished scraping The Devils (The Devils, #1)
no popup
Language: English
finished scraping A Harvest of Hearts
no popup
Language not found.
finished scraping Alchemy of Secrets (Alchemy of Secrets, #1)
no popup
Language not found.
finished scraping Aftertaste
no popup
Language not found.
finished scraping The Woman in Suite 11 (Lo Blacklock, #2)
no popup
Language not found.
finished scraping Black Woods Blue Sky
no popup
Language not found.
finished scraping Wild Reverence
no popup
Language: English
finished scraping You Are Fatally Invited
no popup
Language not found.
finished scraping The Bewitching
no popup
Language not found.
finished scraping It's a Love Story
no popup
Language: English
finished scraping Stag Dance
no popup
Language: English
finished scraping Glorious Rivals (The Grandest Game, #2)
no popup
Language not found.
finished scraping Nine-Tenths
no popup
Language: English
finished scraping A Girl Within a Girl Within a Girl
no popup
Language: English
finished scraping Lessons in Magic and Disaster
no popup
Language: English
finished scraping Fake Skating
no popup
Language: English
finished scraping Coffin Moon
no popup
Language: English
finished scraping Born Equal: Remaking America’s Constitution, 1840–1920
no popup
Language: English
finished scraping Tears of the Wolf (Wrath and Weeping, #1)
no popup
Language: English
finished scraping The Corruption of Hollis Brown
no popup
Language: English
finished scraping Bog Queen
no popup
Language: English
finished scraping The Everlasting
no popup
Language: English
finished scraping Are You Mad at Me?
no popup
Language not found.
finished scraping Separation of Church and Hate: A Sane Person's Guide to Taking Back the Bible from Fundamentalists, Fascists, and Flock-Fleecing Frauds
no popup
Language not found.
finished scraping Vaim
no popup
Language not found.
finished scraping The Loneliness of Sonia and Sunny
no popup
Language: English
finished scraping Mad Mabel
no popup
Language: English
finished scraping The Marriage Method (The Crinoline Academy, #2)
no popup
Language not found.
finished scraping Who Is Government? The Untold Story of Public Service
no popup
Language: English
finished scraping The Incandescent
no popup
Language: English
finished scraping Food Person
no popup
Language not found.
finished scraping 107 Days
no popup
Language not found.
finished scraping Slayers, Every One of Us: How One Girl in All the World Showed Us How to Hold On
no popup
Language: English
finished scraping TERF Island: How the UK Resisted Trans Ideology
no popup
Language not found.
finished scraping Last Rites
no popup
Language: English
finished scraping Cannon
no popup
Language not found.
finished scraping Tourist Season (The Seasons of Carnage Trilogy, #1)
no popup
Language: English
finished scraping Rules for Ruin (The Crinoline Academy, #1)
no popup
Language: English
finished scraping The Cartoonists Club
no popup
Language: English
finished scraping The Works of Vermin
no popup
Language: English
finished scraping Full Bloom
no popup
Language not found.
finished scraping The Loneliness of Sonia and Sunny
no popup
Language: English
finished scraping Red Tempest Brother (The Winter Sea, #3)
no popup
Language: English
finished scraping Marble Hall Murders (Susan Ryeland, #3)
no popup
Language: English
finished scraping Night Watcher
no popup
Language not found.
finished scraping Tongues, Vol. 1
no popup

In [ ]:
# to avoid re-running the data mining code
df.to_csv("./data/raw_data.csv", index=False)

Data Wrangling / Cleaning

In [192]:
df = pd.read_csv("./data/raw_data.csv")
df["language"] = df["language"].replace(np.nan, "")

In [193]:
df["publication_date"] = df["publication_date"].astype(str).str[16:]
df["publication_date"] = pd.to_datetime(df["publication_date"], format="%B %d, %Y",errors="coerce")
df["avg_rating"] = df["ratings"].astype(str).str[:4]
df["avg_rating"] = pd.to_numeric(df["avg_rating"], errors="coerce")
df["num_ratings"]=df["ratings"].str.extract(r"([\d,]+)\s+ratings")
df["num_ratings"]=df["num_ratings"].str.replace(",","").astype(int)
df.drop("ratings", axis=1, inplace=True)
df["num_pages"] = df["num_pages"].str.extract(r"([\d,]+)\s+pages")[0].str.replace(",", "", regex=False).astype("Int64")
df["curr_readers"] = df["curr_readers"].str.extract(r"([\d]+)\s+people").astype("Int64")
df["want_read"] = df["want_read"].str.extract(r"([\d]+)\s+people").astype("Int64")

In [217]:
df.to_csv("data/data.csv", index=False)

EDA

In [216]:
df.head()

,book_title,publication_date,author,genres,num_pages,rank,language,curr_readers,want_read,avg_rating,num_ratings
0,"Sunrise on the Reaping (The Hunger Games, #0.5)",2025-03-18,Suzanne Collins,"Dystopia, Young Adult, Fantasy, Fiction, Audiobook, Science Fiction, Book Club",387,1,,71857,607177,4.50,1131555
1,"Onyx Storm (The Empyrean, #3)",2025-01-21,Rebecca Yarros,"Fantasy, Romantasy, Romance, Audiobook, Dragons, Fiction, Fantasy Romance",544,2,,211783,693630,4.21,1741280
2,Atmosphere,2025-06-03,Taylor Jenkins Reid,"Historical Fiction, Fiction, Romance, Audiobook, Book Club, LGBT, Historical",337,3,English,63050,816568,4.33,766849
3,My Friends,2025-05-06,Fredrik Backman,"Fiction, Book Club, Audiobook, Contemporary, Literary Fiction, Coming Of Age, Friendship",436,4,English,63867,711684,4.36,428065
4,Wild Dark Shore,2025-03-04,Charlotte McConaghy,"Fiction, Mystery, Book Club, Audiobook, Thriller, Mystery Thriller, Literary Fiction",298,5,English,44288,653895,4.10,404074

In [ ]:
df_genres = df[["book_title","genres", "avg_rating"]]
df_genres["genres"] = df_genres["genres"].str.split(", ")
df_genres = df_genres.explode("genres")

,book_title,genres,avg_rating
0,"Sunrise on the Reaping (The Hunger Games, #0.5)",Dystopia,4.50
0,"Sunrise on the Reaping (The Hunger Games, #0.5)",Young Adult,4.50
0,"Sunrise on the Reaping (The Hunger Games, #0.5)",Fantasy,4.50
0,"Sunrise on the Reaping (The Hunger Games, #0.5)",Fiction,4.50
0,"Sunrise on the Reaping (The Hunger Games, #0.5)",Audiobook,4.50
...,...,...,...
550,Retreat,Mystery Thriller,3.69
550,Retreat,Audiobook,3.69
550,Retreat,Fiction,3.69
550,Retreat,Suspense,3.69
550,Retreat,Adult,3.69

In [ ]:
# Most highly-rated genres
genre_rating = df_genres.dropna(subset=["avg_rating"])
genre_rating = genre_rating.groupby(["genres"])["avg_rating"].mean().round(2).reset_index().sort_values(by=["avg_rating"], ascending=False)
genre_rating

                   genres  avg_rating
198        Social Justice        4.59
64             Disability        4.58
91             Futuristic        4.53
225            Werewolves        4.52
24          Autobiography        4.46
..                    ...         ...
132            Literature        3.56
179             Road Trip        3.56
41                College        3.48
100  Graphic Novels Manga        3.34
199          Social Media        3.17

[236 rows x 2 columns]

In [ ]:
# Most popular genres
df_genres["genres"].value_counts()

genres
Fiction                     396
Audiobook                   390
Romance                     195
Fantasy                     186
Mystery                     173
                           ...
Young Adult Romance           1
African American Romance      1
Womens                        1
Monsters                      1
College                       1
Name: count, Length: 237, dtype: int64